### ISSUE TITLE
Does this replace regular Joomla accounts?

### ISSUE THREAD

**Issue by poVoq** [lal12/nextcloud-joomla-auth#4]
Quick question:

Does this allow to *also* login with the account on Nextcloud, or does it completely replace the (existing) Joomla accounts?

Also, what happens if the Nextcloud connection fails? Is the account duplicated in the Joomla database and can be used? What about encrypted passwords in such a case?

Last but not least, can internal and external accounts be linked to slowly transition away from a Joomla only user base to a Nextcloud only userbase? Assuming the answer to the first question is yes, of course :)

Thanks!

**Comment by lal12** [comment]
> Does this allow to also login with the account on Nextcloud, or does it completely replace the (existing) Joomla accounts?

I am not sure what you mean. But if I am right you asking, whether it is possible to login via a nextcloud user and as a joomla user. Then the answer would be yes. Joomla enables you to enable several authentication plugins in the plugin manager. So the credentials are checked in each auth plugin until they are verfied by one plugin or denied by all.

> Also, what happens if the Nextcloud connection fails? Is the account duplicated in the Joomla database and can be used? What about encrypted passwords in such a case?

When I developed the plugin with the default settings it created the same account also locally in the joomla database, after the first login via a nextcloud user. Which means (I am unsure on this) on a failed connection it should still authenticate the user (if the normal joomla auth plugin is enabled as described above). With a switch in the user settings you could disable this behavior. The password was encrypted as any normal joomla password.

But it could be that in newer joomla versions this behaves differently. Since I am not using the plugin anymore I don't know. But I could look into it, in the next days.

> Last but not least, can internal and external accounts be linked to slowly transition away from a Joomla only user base to a Nextcloud only userbase? Assuming the answer to the first question is yes, of course :)

I guess my first paragraph already answers this question.

**Comment by poVoq** [comment]
Ok, thanks that answers it.
